"""
🔧 Setup Script for Agentic Software House
==========================================
Run this once after cloning the repo to set up your environment.

Usage: python setup.py
"""

import os
import subprocess
import sys

def install_requirements():
    """Install required packages."""
    print("\n📦 Installing required packages...")
    packages = [
        "crewai",
        "crewai-tools", 
        "python-dotenv",
        "groq"
    ]
    for package in packages:
        print(f"   Installing {package}...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", package, "-q"])
    print("   ✅ All packages installed!")

def setup_environment():
    print("""
    ╔══════════════════════════════════════════════════════════╗
    ║     🏢 Agentic Software House - Setup Wizard             ║
    ╚══════════════════════════════════════════════════════════╝
    """)
    
    # Check if .env already exists
    if os.path.exists('.env'):
        print("✅ .env file already exists!")
        overwrite = input("   Do you want to overwrite it? (y/n): ").lower()
        if overwrite != 'y':
            print("   Keeping existing .env file.")
            return
    
    print("\n📝 Let's set up your API keys:\n")
    
    # Get Groq API Key
    print("1️⃣  GROQ API Key (REQUIRED)")
    print("   Get yours free at: https://console.groq.com/keys")
    groq_key = input("   Enter your GROQ_API_KEY: ").strip()
    
    if not groq_key:
        print("\n❌ GROQ_API_KEY is required! Please get one at https://console.groq.com/keys")
        return
    
    # Get Serper API Key (optional)
    print("\n2️⃣  SERPER API Key (optional - for web search)")
    print("   Get yours at: https://serper.dev/")
    serper_key = input("   Enter your SERPER_API_KEY (or press Enter to skip): ").strip()
    
    # Create .env file
    with open('.env', 'w') as f:
        f.write("# ============================================\n")
        f.write("# Agentic Software House - API Keys\n")
        f.write("# Generated by setup.py\n")
        f.write("# ============================================\n\n")
        f.write(f"GROQ_API_KEY={groq_key}\n")
        if serper_key:
            f.write(f"SERPER_API_KEY={serper_key}\n")
    
    print("\n" + "="*55)
    print("✅ Setup complete! Your .env file has been created.")
    print("="*55)
    
    # Ask if user wants to install packages
    print("\n📦 Do you want to install required Python packages?")
    install = input("   (y/n): ").lower()
    if install == 'y':
        install_requirements()
    
    print("\n" + "="*55)
    print("🚀 You're all set! Try running:")
    print('   python build.py "build me a snake game"')
    print("="*55)
    print("\n⚠️  Remember: Never commit .env to git!")

if __name__ == "__main__":
    setup_environment()
